### ISSUE TITLE
Is it real time tracking for deep sort? 

### ISSUE THREAD

**Issue by lchunleo** [ilyasmg/sort-deepsort-yolov3-ROS#1]
Hi
Can I check is the deep sort  result is based on real time video stream tracking (it does not come from a video file)? I am trying out the deep sort but kinda of confused as it seem to do the association based on predefined detection test file. 

Thanks

**Comment by ilyasmg** [comment]
Hi, 
it's real time tracking and it is using the detections coming from YOLO, actually the deep_sort implemented in ROS is not using a predefined detection test file but only a pre-trained model. 
You can modify it to generate your own detection test file for doing tracking on custom images.
Anyway, this repository is just a wrap of sort and deep_sort on a ROS package. For more detailed questions about sort or deep_sort ask here:
sort -> https://github.com/abewley/sort
deep_sort -> https://github.com/nwojke/deep_sort
