### ISSUE TITLE
How to get the weight of deep_sort?

### ISSUE THREAD

**Issue by lrxiao** [ilyasmg/sort-deepsort-yolov3-ROS#3]

**Comment by ilyasmg** [comment]
I don't understand what do you mean by weight of deep_sort. Anyway, this repository is just a wrap of sort and deep_sort on a ROS package. For more detailed questions about sort or deep_sort ask here:
sort -> https://github.com/abewley/sort
deep_sort -> https://github.com/nwojke/deep_sort
