### ISSUE TITLE
Numba Python 3 Support

### ISSUE THREAD

**Issue by edmuthiah** [ilyasmg/sort-deepsort-yolov3-ROS#5]
Hi @ilyasmg 

I've noticed that since 0.47.0 numba only supports Python 3, and your track.py file uses Python 2 through the shebang `#!/usr/bin/env python.` Simple changing this to Python 3 does not seems to work as ROS Melodic doesn't support Python 3.  When I do this I get the following error:

```
File "/home/ed-muthiah/catkin_ws/src/sort-deepsort-yolov3-ROS/sort_track/src/track.py", line 75
    rate = rospy.Rate(10)
                        ^
TabError: inconsistent use of tabs and spaces in indentation
```
Any suggestions to get this repo working for Python 3? Happy to help where I can :)

If there is particular version of numba, llvmlite, and other dependencies that still works please list them!

**Comment by ilyasmg** [comment]
Hi @ed-muthiah,
actually this repo was done using ROS Kinetic and python 2 and when I used it last year I had no problem.
Concerning the error that you got, it's a problem of indentation and spaces.
Also if you want to use Python3 try to use a virtual environment for the python dependencies on ROS.
If you make some progress you can do a PR

**Comment by ilyasmg** [comment]
I added a new branch for porting it to python3. If you want to help, look at #8
