### ISSUE TITLE
Can modify darknet_ros subscribe the datatype of the image format ? I want to use the format of sensor_msgs/CompressedImage rather than sensor_msgs/Image

### ISSUE THREAD

**Issue by sunt40** [ilyasmg/sort-deepsort-yolov3-ROS#6]

**Comment by ilyasmg** [comment]
Yes, you can modify it. Feel free to fork and modify it. Then you can make a pull requests

**Comment by sunt40** [comment]
ok. Can you tell me which part I should modify? I'm not very familiar with Daeknet
