### ISSUE TITLE
A problem with the deep sort package 

### ISSUE THREAD

**Issue by kareem-93** [ilyasmg/sort-deepsort-yolov3-ROS#7]
Hello ilyas, 

Thanks alot for your great work and effort. I knew that this package is no more supported, but i am using your code in my master thesis project and i am stuck in a point where i can not go ahead since 2 weeks. if you can help me i would be really thankful for you !
![Screenshot from 2020-12-20 20-12-11](https://user-images.githubusercontent.com/58070021/102751396-f4a3cc80-4367-11eb-9571-ea09efd6a30d.png)
![Screenshot from 2020-12-20 19-23-46](https://user-images.githubusercontent.com/58070021/102751432-0ab18d00-4368-11eb-92ca-62b02d3e47ac.png)

**Comment by ilyasmg** [comment]
Hey, I fixed the IndentationError but there are still dependencies problems with python2. I think you should try to do it with python3 and ROS Noetic. Look at this issue for more details #8 
I also added a docker environment for both ROS kinetic and ROS noetic to use instead of installing locally

**Comment by kareem-93** [comment]
Thanks alot for your quick respond, i have used it with ROS kinetic and python 2.7. The reason for that is the ardrone driver for for AR.Drone  2.0 is provided for ros kinetic only. Anyway thanks alot for your help, i really appreciate it. I will try it and will keep you updated. Did u also post your code for the PID controller somewhere on Github ?
